/// Static, offline list of countries (ISO 3166-1 alpha-2 codes) for the
/// nationalité dropdown. Never fetched live — bundled with the app,
/// same pattern as reference_data.dart for régions/communes.
///
/// Guinea is listed first since it's the overwhelmingly common case for
/// this app's user base; the rest are alphabetical by French name.
library;

class CountryData {
  const CountryData({required this.code, required this.nom});
  final String code;
  final String nom;
}

const List<CountryData> countriesData = [
  CountryData(code: 'GN', nom: 'Guinée'),
  CountryData(code: 'AF', nom: 'Afghanistan'),
  CountryData(code: 'ZA', nom: 'Afrique du Sud'),
  CountryData(code: 'AL', nom: 'Albanie'),
  CountryData(code: 'DZ', nom: 'Algérie'),
  CountryData(code: 'DE', nom: 'Allemagne'),
  CountryData(code: 'AD', nom: 'Andorre'),
  CountryData(code: 'AO', nom: 'Angola'),
  CountryData(code: 'SA', nom: 'Arabie Saoudite'),
  CountryData(code: 'AR', nom: 'Argentine'),
  CountryData(code: 'AM', nom: 'Arménie'),
  CountryData(code: 'AU', nom: 'Australie'),
  CountryData(code: 'AT', nom: 'Autriche'),
  CountryData(code: 'AZ', nom: 'Azerbaïdjan'),
  CountryData(code: 'BS', nom: 'Bahamas'),
  CountryData(code: 'BH', nom: 'Bahreïn'),
  CountryData(code: 'BD', nom: 'Bangladesh'),
  CountryData(code: 'BE', nom: 'Belgique'),
  CountryData(code: 'BJ', nom: 'Bénin'),
  CountryData(code: 'BT', nom: 'Bhoutan'),
  CountryData(code: 'BY', nom: 'Biélorussie'),
  CountryData(code: 'MM', nom: 'Birmanie'),
  CountryData(code: 'BO', nom: 'Bolivie'),
  CountryData(code: 'BA', nom: 'Bosnie-Herzégovine'),
  CountryData(code: 'BW', nom: 'Botswana'),
  CountryData(code: 'BR', nom: 'Brésil'),
  CountryData(code: 'BN', nom: 'Brunei'),
  CountryData(code: 'BG', nom: 'Bulgarie'),
  CountryData(code: 'BF', nom: 'Burkina Faso'),
  CountryData(code: 'BI', nom: 'Burundi'),
  CountryData(code: 'KH', nom: 'Cambodge'),
  CountryData(code: 'CM', nom: 'Cameroun'),
  CountryData(code: 'CA', nom: 'Canada'),
  CountryData(code: 'CV', nom: 'Cap-Vert'),
  CountryData(code: 'CF', nom: 'République centrafricaine'),
  CountryData(code: 'CL', nom: 'Chili'),
  CountryData(code: 'CN', nom: 'Chine'),
  CountryData(code: 'CY', nom: 'Chypre'),
  CountryData(code: 'CO', nom: 'Colombie'),
  CountryData(code: 'KM', nom: 'Comores'),
  CountryData(code: 'CG', nom: 'Congo'),
  CountryData(code: 'CD', nom: 'Congo (RDC)'),
  CountryData(code: 'KR', nom: 'Corée du Sud'),
  CountryData(code: 'KP', nom: 'Corée du Nord'),
  CountryData(code: 'CR', nom: 'Costa Rica'),
  CountryData(code: 'CI', nom: "Côte d'Ivoire"),
  CountryData(code: 'HR', nom: 'Croatie'),
  CountryData(code: 'CU', nom: 'Cuba'),
  CountryData(code: 'DK', nom: 'Danemark'),
  CountryData(code: 'DJ', nom: 'Djibouti'),
  CountryData(code: 'EG', nom: 'Égypte'),
  CountryData(code: 'AE', nom: 'Émirats Arabes Unis'),
  CountryData(code: 'EC', nom: 'Équateur'),
  CountryData(code: 'ER', nom: 'Érythrée'),
  CountryData(code: 'ES', nom: 'Espagne'),
  CountryData(code: 'EE', nom: 'Estonie'),
  CountryData(code: 'SZ', nom: 'Eswatini'),
  CountryData(code: 'US', nom: 'États-Unis'),
  CountryData(code: 'ET', nom: 'Éthiopie'),
  CountryData(code: 'FJ', nom: 'Fidji'),
  CountryData(code: 'FI', nom: 'Finlande'),
  CountryData(code: 'FR', nom: 'France'),
  CountryData(code: 'GA', nom: 'Gabon'),
  CountryData(code: 'GM', nom: 'Gambie'),
  CountryData(code: 'GE', nom: 'Géorgie'),
  CountryData(code: 'GH', nom: 'Ghana'),
  CountryData(code: 'GR', nom: 'Grèce'),
  CountryData(code: 'GD', nom: 'Grenade'),
  CountryData(code: 'GT', nom: 'Guatemala'),
  CountryData(code: 'GW', nom: 'Guinée-Bissau'),
  CountryData(code: 'GQ', nom: 'Guinée équatoriale'),
  CountryData(code: 'GY', nom: 'Guyana'),
  CountryData(code: 'HT', nom: 'Haïti'),
  CountryData(code: 'HN', nom: 'Honduras'),
  CountryData(code: 'HU', nom: 'Hongrie'),
  CountryData(code: 'IN', nom: 'Inde'),
  CountryData(code: 'ID', nom: 'Indonésie'),
  CountryData(code: 'IQ', nom: 'Irak'),
  CountryData(code: 'IR', nom: 'Iran'),
  CountryData(code: 'IE', nom: 'Irlande'),
  CountryData(code: 'IS', nom: 'Islande'),
  CountryData(code: 'IL', nom: 'Israël'),
  CountryData(code: 'IT', nom: 'Italie'),
  CountryData(code: 'JM', nom: 'Jamaïque'),
  CountryData(code: 'JP', nom: 'Japon'),
  CountryData(code: 'JO', nom: 'Jordanie'),
  CountryData(code: 'KZ', nom: 'Kazakhstan'),
  CountryData(code: 'KE', nom: 'Kenya'),
  CountryData(code: 'KG', nom: 'Kirghizistan'),
  CountryData(code: 'KW', nom: 'Koweït'),
  CountryData(code: 'LA', nom: 'Laos'),
  CountryData(code: 'LS', nom: 'Lesotho'),
  CountryData(code: 'LV', nom: 'Lettonie'),
  CountryData(code: 'LB', nom: 'Liban'),
  CountryData(code: 'LR', nom: 'Libéria'),
  CountryData(code: 'LY', nom: 'Libye'),
  CountryData(code: 'LI', nom: 'Liechtenstein'),
  CountryData(code: 'LT', nom: 'Lituanie'),
  CountryData(code: 'LU', nom: 'Luxembourg'),
  CountryData(code: 'MK', nom: 'Macédoine du Nord'),
  CountryData(code: 'MG', nom: 'Madagascar'),
  CountryData(code: 'MY', nom: 'Malaisie'),
  CountryData(code: 'MW', nom: 'Malawi'),
  CountryData(code: 'MV', nom: 'Maldives'),
  CountryData(code: 'ML', nom: 'Mali'),
  CountryData(code: 'MT', nom: 'Malte'),
  CountryData(code: 'MA', nom: 'Maroc'),
  CountryData(code: 'MU', nom: 'Maurice'),
  CountryData(code: 'MR', nom: 'Mauritanie'),
  CountryData(code: 'MX', nom: 'Mexique'),
  CountryData(code: 'MD', nom: 'Moldavie'),
  CountryData(code: 'MC', nom: 'Monaco'),
  CountryData(code: 'MN', nom: 'Mongolie'),
  CountryData(code: 'ME', nom: 'Monténégro'),
  CountryData(code: 'MZ', nom: 'Mozambique'),
  CountryData(code: 'NA', nom: 'Namibie'),
  CountryData(code: 'NP', nom: 'Népal'),
  CountryData(code: 'NI', nom: 'Nicaragua'),
  CountryData(code: 'NE', nom: 'Niger'),
  CountryData(code: 'NG', nom: 'Nigéria'),
  CountryData(code: 'NO', nom: 'Norvège'),
  CountryData(code: 'NZ', nom: 'Nouvelle-Zélande'),
  CountryData(code: 'OM', nom: 'Oman'),
  CountryData(code: 'UG', nom: 'Ouganda'),
  CountryData(code: 'UZ', nom: 'Ouzbékistan'),
  CountryData(code: 'PK', nom: 'Pakistan'),
  CountryData(code: 'PA', nom: 'Panama'),
  CountryData(code: 'PG', nom: 'Papouasie-Nouvelle-Guinée'),
  CountryData(code: 'PY', nom: 'Paraguay'),
  CountryData(code: 'NL', nom: 'Pays-Bas'),
  CountryData(code: 'PE', nom: 'Pérou'),
  CountryData(code: 'PH', nom: 'Philippines'),
  CountryData(code: 'PL', nom: 'Pologne'),
  CountryData(code: 'PT', nom: 'Portugal'),
  CountryData(code: 'QA', nom: 'Qatar'),
  CountryData(code: 'RO', nom: 'Roumanie'),
  CountryData(code: 'GB', nom: 'Royaume-Uni'),
  CountryData(code: 'RU', nom: 'Russie'),
  CountryData(code: 'RW', nom: 'Rwanda'),
  CountryData(code: 'SV', nom: 'Salvador'),
  CountryData(code: 'WS', nom: 'Samoa'),
  CountryData(code: 'SN', nom: 'Sénégal'),
  CountryData(code: 'RS', nom: 'Serbie'),
  CountryData(code: 'SC', nom: 'Seychelles'),
  CountryData(code: 'SL', nom: 'Sierra Leone'),
  CountryData(code: 'SG', nom: 'Singapour'),
  CountryData(code: 'SK', nom: 'Slovaquie'),
  CountryData(code: 'SI', nom: 'Slovénie'),
  CountryData(code: 'SO', nom: 'Somalie'),
  CountryData(code: 'SD', nom: 'Soudan'),
  CountryData(code: 'SS', nom: 'Soudan du Sud'),
  CountryData(code: 'LK', nom: 'Sri Lanka'),
  CountryData(code: 'SE', nom: 'Suède'),
  CountryData(code: 'CH', nom: 'Suisse'),
  CountryData(code: 'SR', nom: 'Suriname'),
  CountryData(code: 'SY', nom: 'Syrie'),
  CountryData(code: 'TJ', nom: 'Tadjikistan'),
  CountryData(code: 'TZ', nom: 'Tanzanie'),
  CountryData(code: 'TD', nom: 'Tchad'),
  CountryData(code: 'CZ', nom: 'Tchéquie'),
  CountryData(code: 'TH', nom: 'Thaïlande'),
  CountryData(code: 'TG', nom: 'Togo'),
  CountryData(code: 'TN', nom: 'Tunisie'),
  CountryData(code: 'TM', nom: 'Turkménistan'),
  CountryData(code: 'TR', nom: 'Turquie'),
  CountryData(code: 'UA', nom: 'Ukraine'),
  CountryData(code: 'UY', nom: 'Uruguay'),
  CountryData(code: 'VE', nom: 'Venezuela'),
  CountryData(code: 'VN', nom: 'Vietnam'),
  CountryData(code: 'YE', nom: 'Yémen'),
  CountryData(code: 'ZM', nom: 'Zambie'),
  CountryData(code: 'ZW', nom: 'Zimbabwe'),
];

CountryData? findCountry(String code) {
  for (final c in countriesData) {
    if (c.code == code) return c;
  }
  return null;
}
