/// Static, offline copy of the Region/Commune/SousPrefecture reference
/// data — mirrors the exact rows inserted by seedRegions/seedCommunes/
/// seedSousPrefectures. This file exists so dropdown fields never need
/// a live listerRegions/listerCommunes/listerSousPrefectures call —
/// the data is bundled with the app and never changes at runtime.
///
/// If the backend reference data is ever amended (new commune added,
/// renamed, etc.), this file must be updated to match — there is no
/// automatic sync between this file and the deployed database.
library;

class RegionData {
  const RegionData({required this.id, required this.nom});
  final int id;
  final String nom;
}

class CommuneData {
  const CommuneData({
    required this.id,
    required this.nom,
    required this.regionId,
  });
  final int id;
  final String nom;
  final int regionId;
}

class SousPrefectureData {
  const SousPrefectureData({
    required this.id,
    required this.nom,
    required this.communeId,
  });
  final int id;
  final String nom;
  final int communeId;
}

const List<RegionData> regionsData = [
  RegionData(id: 1, nom: "Boke"),
  RegionData(id: 2, nom: "Conakry"),
  RegionData(id: 3, nom: "Faranah"),
  RegionData(id: 4, nom: "Kankan"),
  RegionData(id: 5, nom: "Kindia"),
  RegionData(id: 6, nom: "Labe"),
  RegionData(id: 7, nom: "Mamou"),
  RegionData(id: 8, nom: "N'Zerekore"),
];

const List<CommuneData> communesData = [
  CommuneData(id: 1, nom: "BEYLA", regionId: 8),
  CommuneData(id: 2, nom: "BOFFA", regionId: 1),
  CommuneData(id: 3, nom: "BOKE", regionId: 1),
  CommuneData(id: 4, nom: "CONAKRY", regionId: 2),
  CommuneData(id: 5, nom: "COYAH", regionId: 5),
  CommuneData(id: 6, nom: "DABOLA", regionId: 3),
  CommuneData(id: 7, nom: "DALABA", regionId: 7),
  CommuneData(id: 8, nom: "DINGUIRAYE", regionId: 3),
  CommuneData(id: 9, nom: "DUBREKA", regionId: 5),
  CommuneData(id: 10, nom: "FARANAH", regionId: 3),
  CommuneData(id: 11, nom: "FORECARIAH", regionId: 5),
  CommuneData(id: 12, nom: "FRIA", regionId: 1),
  CommuneData(id: 13, nom: "GAOUAL", regionId: 1),
  CommuneData(id: 14, nom: "GUECKEDOU", regionId: 8),
  CommuneData(id: 15, nom: "KANKAN", regionId: 4),
  CommuneData(id: 16, nom: "KEROUANE", regionId: 4),
  CommuneData(id: 17, nom: "KINDIA", regionId: 5),
  CommuneData(id: 18, nom: "KISSIDOUGOU", regionId: 3),
  CommuneData(id: 19, nom: "KOUBIA", regionId: 6),
  CommuneData(id: 20, nom: "KOUNDARA", regionId: 1),
  CommuneData(id: 21, nom: "KOUROUSSA", regionId: 4),
  CommuneData(id: 22, nom: "LABE", regionId: 6),
  CommuneData(id: 23, nom: "LELOUMA", regionId: 6),
  CommuneData(id: 24, nom: "LOLA", regionId: 8),
  CommuneData(id: 25, nom: "MACENTA", regionId: 8),
  CommuneData(id: 26, nom: "MALI", regionId: 6),
  CommuneData(id: 27, nom: "MAMOU", regionId: 7),
  CommuneData(id: 28, nom: "MANDIANA", regionId: 4),
  CommuneData(id: 29, nom: "N'ZEREKORE", regionId: 8),
  CommuneData(id: 30, nom: "PITA", regionId: 7),
  CommuneData(id: 31, nom: "SIGUIRI", regionId: 4),
  CommuneData(id: 32, nom: "TELIMELE", regionId: 5),
  CommuneData(id: 33, nom: "TOUGUE", regionId: 6),
  CommuneData(id: 34, nom: "YOMOU", regionId: 8),
];

const List<SousPrefectureData> sousPrefecturesData = [
  SousPrefectureData(id: 1, nom: "Boffa-Centre", communeId: 2),
  SousPrefectureData(id: 2, nom: "Colia", communeId: 2),
  SousPrefectureData(id: 3, nom: "Doupro", communeId: 2),
  SousPrefectureData(id: 4, nom: "Koba-Tatema", communeId: 2),
  SousPrefectureData(id: 5, nom: "Lisso", communeId: 2),
  SousPrefectureData(id: 6, nom: "Mankountan", communeId: 2),
  SousPrefectureData(id: 7, nom: "Tamita", communeId: 2),
  SousPrefectureData(id: 8, nom: "Tougnifili", communeId: 2),
  SousPrefectureData(id: 9, nom: "Bintimodiya", communeId: 3),
  SousPrefectureData(id: 10, nom: "Boke-Centre", communeId: 3),
  SousPrefectureData(id: 11, nom: "Dabiss", communeId: 3),
  SousPrefectureData(id: 12, nom: "Kamsar", communeId: 3),
  SousPrefectureData(id: 13, nom: "Kanfarande", communeId: 3),
  SousPrefectureData(id: 14, nom: "Kolaboui", communeId: 3),
  SousPrefectureData(id: 15, nom: "Malapouyah", communeId: 3),
  SousPrefectureData(id: 16, nom: "Sangaredi", communeId: 3),
  SousPrefectureData(id: 17, nom: "Sansale", communeId: 3),
  SousPrefectureData(id: 18, nom: "Tanene", communeId: 3),
  SousPrefectureData(id: 19, nom: "Baguinet", communeId: 12),
  SousPrefectureData(id: 20, nom: "Banguingny", communeId: 12),
  SousPrefectureData(id: 21, nom: "Fria-Centre", communeId: 12),
  SousPrefectureData(id: 22, nom: "Tormelin", communeId: 12),
  SousPrefectureData(id: 23, nom: "Foulamory", communeId: 13),
  SousPrefectureData(id: 24, nom: "Gaoual-Centre", communeId: 13),
  SousPrefectureData(id: 25, nom: "Kakony", communeId: 13),
  SousPrefectureData(id: 26, nom: "Koumbia", communeId: 13),
  SousPrefectureData(id: 27, nom: "Kounsitel", communeId: 13),
  SousPrefectureData(id: 28, nom: "Malanta", communeId: 13),
  SousPrefectureData(id: 29, nom: "Touba", communeId: 13),
  SousPrefectureData(id: 30, nom: "Wendou M'bour", communeId: 13),
  SousPrefectureData(id: 31, nom: "Guingan", communeId: 20),
  SousPrefectureData(id: 32, nom: "Kamaby", communeId: 20),
  SousPrefectureData(id: 33, nom: "Koundara-Centre", communeId: 20),
  SousPrefectureData(id: 34, nom: "Sambailo", communeId: 20),
  SousPrefectureData(id: 35, nom: "Sareboido", communeId: 20),
  SousPrefectureData(id: 36, nom: "Termesse", communeId: 20),
  SousPrefectureData(id: 37, nom: "Youkounkoun", communeId: 20),
  SousPrefectureData(id: 38, nom: "Dixinn", communeId: 4),
  SousPrefectureData(id: 39, nom: "Kaloum", communeId: 4),
  SousPrefectureData(id: 40, nom: "Matam", communeId: 4),
  SousPrefectureData(id: 41, nom: "Matoto", communeId: 4),
  SousPrefectureData(id: 42, nom: "Ratoma", communeId: 4),
  SousPrefectureData(id: 43, nom: "Kassa", communeId: 4),
  SousPrefectureData(id: 44, nom: "Arfamoussaya", communeId: 6),
  SousPrefectureData(id: 45, nom: "Banko", communeId: 6),
  SousPrefectureData(id: 46, nom: "Bissikrima", communeId: 6),
  SousPrefectureData(id: 47, nom: "Dabola-centre", communeId: 6),
  SousPrefectureData(id: 48, nom: "Dogomet", communeId: 6),
  SousPrefectureData(id: 49, nom: "Kankama", communeId: 6),
  SousPrefectureData(id: 50, nom: "Kindoye", communeId: 6),
  SousPrefectureData(id: 51, nom: "Konindou", communeId: 6),
  SousPrefectureData(id: 52, nom: "N'Dema", communeId: 6),
  SousPrefectureData(id: 53, nom: "Banora", communeId: 8),
  SousPrefectureData(id: 54, nom: "Dialakoro", communeId: 8),
  SousPrefectureData(id: 55, nom: "Diatifere", communeId: 8),
  SousPrefectureData(id: 56, nom: "Dinguiraye-centre", communeId: 8),
  SousPrefectureData(id: 57, nom: "Gagnakali", communeId: 8),
  SousPrefectureData(id: 58, nom: "Kalinko", communeId: 8),
  SousPrefectureData(id: 59, nom: "Lansanya", communeId: 8),
  SousPrefectureData(id: 60, nom: "Selouma", communeId: 8),
  SousPrefectureData(id: 61, nom: "Ballaya", communeId: 10),
  SousPrefectureData(id: 62, nom: "Bambaya", communeId: 10),
  SousPrefectureData(id: 63, nom: "Bantoun", communeId: 10),
  SousPrefectureData(id: 64, nom: "Banian", communeId: 10),
  SousPrefectureData(id: 65, nom: "Beindou", communeId: 10),
  SousPrefectureData(id: 66, nom: "Dantiliy", communeId: 10),
  SousPrefectureData(id: 67, nom: "Faranah-centre", communeId: 10),
  SousPrefectureData(id: 68, nom: "Gnaleah", communeId: 10),
  SousPrefectureData(id: 69, nom: "Heremakonon", communeId: 10),
  SousPrefectureData(id: 70, nom: "Kobikoro", communeId: 10),
  SousPrefectureData(id: 71, nom: "Marela", communeId: 10),
  SousPrefectureData(id: 72, nom: "Passayah", communeId: 10),
  SousPrefectureData(id: 73, nom: "sandeniah", communeId: 10),
  SousPrefectureData(id: 74, nom: "Songoyah", communeId: 10),
  SousPrefectureData(id: 75, nom: "Tindo", communeId: 10),
  SousPrefectureData(id: 76, nom: "Tiro", communeId: 10),
  SousPrefectureData(id: 77, nom: "Albadariah", communeId: 18),
  SousPrefectureData(id: 78, nom: "Banama", communeId: 18),
  SousPrefectureData(id: 79, nom: "Bardou", communeId: 18),
  SousPrefectureData(id: 80, nom: "Beindou", communeId: 18),
  SousPrefectureData(id: 81, nom: "Fermesadou", communeId: 18),
  SousPrefectureData(id: 82, nom: "Firawa (Yomadou)", communeId: 18),
  SousPrefectureData(id: 83, nom: "Gbangbadou", communeId: 18),
  SousPrefectureData(id: 84, nom: "kissidougou Centre", communeId: 18),
  SousPrefectureData(id: 85, nom: "Koundiatou", communeId: 18),
  SousPrefectureData(id: 86, nom: "Manfran", communeId: 18),
  SousPrefectureData(id: 87, nom: "Sangardo", communeId: 18),
  SousPrefectureData(id: 88, nom: "Yende-Millimou", communeId: 18),
  SousPrefectureData(id: 89, nom: "Yombiro", communeId: 18),
  SousPrefectureData(id: 90, nom: "Balandougou", communeId: 15),
  SousPrefectureData(id: 91, nom: "Bate-nafadji", communeId: 15),
  SousPrefectureData(id: 92, nom: "Boula", communeId: 15),
  SousPrefectureData(id: 93, nom: "Gberedou-Baranama", communeId: 15),
  SousPrefectureData(id: 94, nom: "Kankan-centre", communeId: 15),
  SousPrefectureData(id: 95, nom: "Karifamoriyah", communeId: 15),
  SousPrefectureData(id: 96, nom: "Koumban", communeId: 15),
  SousPrefectureData(id: 97, nom: "Mamouroudou", communeId: 15),
  SousPrefectureData(id: 98, nom: "Missamana", communeId: 15),
  SousPrefectureData(id: 99, nom: "Moribayah", communeId: 15),
  SousPrefectureData(id: 100, nom: "Sabadou-Baranama", communeId: 15),
  SousPrefectureData(id: 101, nom: "Tinti-Oulen", communeId: 15),
  SousPrefectureData(id: 102, nom: "Tokounou", communeId: 15),
  SousPrefectureData(id: 103, nom: "Banankoro", communeId: 16),
  SousPrefectureData(id: 104, nom: "Damaro", communeId: 16),
  SousPrefectureData(id: 105, nom: "Kereouane centre", communeId: 16),
  SousPrefectureData(id: 106, nom: "Komodou", communeId: 16),
  SousPrefectureData(id: 107, nom: "Kounsankoro", communeId: 16),
  SousPrefectureData(id: 108, nom: "Linko", communeId: 16),
  SousPrefectureData(id: 109, nom: "Sibiribaro", communeId: 16),
  SousPrefectureData(id: 110, nom: "Soromaya", communeId: 16),
  SousPrefectureData(id: 111, nom: "Babila", communeId: 21),
  SousPrefectureData(id: 112, nom: "Balato", communeId: 21),
  SousPrefectureData(id: 113, nom: "Banfele", communeId: 21),
  SousPrefectureData(id: 114, nom: "Baro", communeId: 21),
  SousPrefectureData(id: 115, nom: "Cissela", communeId: 21),
  SousPrefectureData(id: 116, nom: "Douako", communeId: 21),
  SousPrefectureData(id: 117, nom: "Doura", communeId: 21),
  SousPrefectureData(id: 118, nom: "Kiniero", communeId: 21),
  SousPrefectureData(id: 119, nom: "Komola-Koura", communeId: 21),
  SousPrefectureData(id: 120, nom: "Koumana", communeId: 21),
  SousPrefectureData(id: 121, nom: "Kouroussa centre", communeId: 21),
  SousPrefectureData(id: 122, nom: "Sanguiana", communeId: 21),
  SousPrefectureData(id: 123, nom: "Balandougouba", communeId: 28),
  SousPrefectureData(id: 124, nom: "Dialakoro", communeId: 28),
  SousPrefectureData(id: 125, nom: "Faralako", communeId: 28),
  SousPrefectureData(id: 126, nom: "Kantoumanina", communeId: 28),
  SousPrefectureData(id: 127, nom: "Kinieran", communeId: 28),
  SousPrefectureData(id: 128, nom: "Kondianakoro", communeId: 28),
  SousPrefectureData(id: 129, nom: "Koundian", communeId: 28),
  SousPrefectureData(id: 130, nom: "Mandiana-centre", communeId: 28),
  SousPrefectureData(id: 131, nom: "Morodou", communeId: 28),
  SousPrefectureData(id: 132, nom: "Niantania", communeId: 28),
  SousPrefectureData(id: 133, nom: "Saladou", communeId: 28),
  SousPrefectureData(id: 134, nom: "Sansando", communeId: 28),
  SousPrefectureData(id: 135, nom: "Bankon", communeId: 31),
  SousPrefectureData(id: 136, nom: "Doko", communeId: 31),
  SousPrefectureData(id: 137, nom: "Franwalia", communeId: 31),
  SousPrefectureData(id: 138, nom: "Kiniebakoura", communeId: 31),
  SousPrefectureData(id: 139, nom: "Kintinian", communeId: 31),
  SousPrefectureData(id: 140, nom: "Malea", communeId: 31),
  SousPrefectureData(id: 141, nom: "Naboun", communeId: 31),
  SousPrefectureData(id: 142, nom: "Niagassola", communeId: 31),
  SousPrefectureData(id: 143, nom: "Niandankoro", communeId: 31),
  SousPrefectureData(id: 144, nom: "Norassoba", communeId: 31),
  SousPrefectureData(id: 145, nom: "Nounkounkan", communeId: 31),
  SousPrefectureData(id: 146, nom: "Siguiri-centre", communeId: 31),
  SousPrefectureData(id: 147, nom: "Siguirini", communeId: 31),
  SousPrefectureData(id: 148, nom: "Coyah centre", communeId: 5),
  SousPrefectureData(id: 149, nom: "Kouriya", communeId: 5),
  SousPrefectureData(id: 150, nom: "Maneah", communeId: 5),
  SousPrefectureData(id: 151, nom: "Wonkifong", communeId: 5),
  SousPrefectureData(id: 152, nom: "Badi", communeId: 9),
  SousPrefectureData(id: 153, nom: "Dubreka-centre", communeId: 9),
  SousPrefectureData(id: 154, nom: "Falessade", communeId: 9),
  SousPrefectureData(id: 155, nom: "Khorira", communeId: 9),
  SousPrefectureData(id: 156, nom: "Ouassou", communeId: 9),
  SousPrefectureData(id: 157, nom: "Tanene", communeId: 9),
  SousPrefectureData(id: 158, nom: "Tondon", communeId: 9),
  SousPrefectureData(id: 159, nom: "Alassoya", communeId: 11),
  SousPrefectureData(id: 160, nom: "Benty", communeId: 11),
  SousPrefectureData(id: 161, nom: "Farmoriah", communeId: 11),
  SousPrefectureData(id: 162, nom: "Forecareah Centre", communeId: 11),
  SousPrefectureData(id: 163, nom: "Kaback", communeId: 11),
  SousPrefectureData(id: 164, nom: "Kakossa", communeId: 11),
  SousPrefectureData(id: 165, nom: "Kallia", communeId: 11),
  SousPrefectureData(id: 166, nom: "Maferenya", communeId: 11),
  SousPrefectureData(id: 167, nom: "Moussaya", communeId: 11),
  SousPrefectureData(id: 168, nom: "Sikhourou", communeId: 11),
  SousPrefectureData(id: 169, nom: "Bangouyah", communeId: 17),
  SousPrefectureData(id: 170, nom: "Damankanyah", communeId: 17),
  SousPrefectureData(id: 171, nom: "Friguiagbe", communeId: 17),
  SousPrefectureData(id: 172, nom: "Kindia centre", communeId: 17),
  SousPrefectureData(id: 173, nom: "Kolente", communeId: 17),
  SousPrefectureData(id: 174, nom: "Lynsan", communeId: 17),
  SousPrefectureData(id: 175, nom: "Madina Oula", communeId: 17),
  SousPrefectureData(id: 176, nom: "Mambiya", communeId: 17),
  SousPrefectureData(id: 177, nom: "Molota", communeId: 17),
  SousPrefectureData(id: 178, nom: "Samayah", communeId: 17),
  SousPrefectureData(id: 179, nom: "Sougueta", communeId: 17),
  SousPrefectureData(id: 180, nom: "Bourouwal", communeId: 32),
  SousPrefectureData(id: 181, nom: "Daramagnaky", communeId: 32),
  SousPrefectureData(id: 182, nom: "Gougoudje", communeId: 32),
  SousPrefectureData(id: 183, nom: "Koba", communeId: 32),
  SousPrefectureData(id: 184, nom: "Kollet", communeId: 32),
  SousPrefectureData(id: 185, nom: "Konsotamy", communeId: 32),
  SousPrefectureData(id: 186, nom: "Missira", communeId: 32),
  SousPrefectureData(id: 187, nom: "Santou", communeId: 32),
  SousPrefectureData(id: 188, nom: "Sarekaly", communeId: 32),
  SousPrefectureData(id: 189, nom: "Sinta", communeId: 32),
  SousPrefectureData(id: 190, nom: "Sogolon", communeId: 32),
  SousPrefectureData(id: 191, nom: "Tarihoye", communeId: 32),
  SousPrefectureData(id: 192, nom: "Telimele centre", communeId: 32),
  SousPrefectureData(id: 193, nom: "Thionthian", communeId: 32),
  SousPrefectureData(id: 194, nom: "Fafaya", communeId: 19),
  SousPrefectureData(id: 195, nom: "Gadha Woundou", communeId: 19),
  SousPrefectureData(id: 196, nom: "Koubia centre", communeId: 19),
  SousPrefectureData(id: 197, nom: "Matakaou", communeId: 19),
  SousPrefectureData(id: 198, nom: "Missira", communeId: 19),
  SousPrefectureData(id: 199, nom: "Pilimini", communeId: 19),
  SousPrefectureData(id: 200, nom: "Dalein", communeId: 22),
  SousPrefectureData(id: 201, nom: "Daralabe", communeId: 22),
  SousPrefectureData(id: 202, nom: "Diari", communeId: 22),
  SousPrefectureData(id: 203, nom: "Dionfo", communeId: 22),
  SousPrefectureData(id: 204, nom: "Garambe", communeId: 22),
  SousPrefectureData(id: 205, nom: "Hafia", communeId: 22),
  SousPrefectureData(id: 206, nom: "Kaalan", communeId: 22),
  SousPrefectureData(id: 207, nom: "Kouramangui", communeId: 22),
  SousPrefectureData(id: 208, nom: "Labe centre", communeId: 22),
  SousPrefectureData(id: 209, nom: "Noussy", communeId: 22),
  SousPrefectureData(id: 210, nom: "Popodara", communeId: 22),
  SousPrefectureData(id: 211, nom: "Sannoun", communeId: 22),
  SousPrefectureData(id: 212, nom: "Taranbaly", communeId: 22),
  SousPrefectureData(id: 213, nom: "Tountouroun", communeId: 22),
  SousPrefectureData(id: 214, nom: "Balaya", communeId: 23),
  SousPrefectureData(id: 215, nom: "Djountou", communeId: 23),
  SousPrefectureData(id: 216, nom: "Herico", communeId: 23),
  SousPrefectureData(id: 217, nom: "Korbe", communeId: 23),
  SousPrefectureData(id: 218, nom: "Lafou", communeId: 23),
  SousPrefectureData(id: 219, nom: "Lelouma centre", communeId: 23),
  SousPrefectureData(id: 220, nom: "Linsansaran", communeId: 23),
  SousPrefectureData(id: 221, nom: "Manda", communeId: 23),
  SousPrefectureData(id: 222, nom: "Parawol", communeId: 23),
  SousPrefectureData(id: 223, nom: "Sagale", communeId: 23),
  SousPrefectureData(id: 224, nom: "Tyanguel-Bori", communeId: 23),
  SousPrefectureData(id: 225, nom: "Balaki", communeId: 26),
  SousPrefectureData(id: 226, nom: "Donghol Sigon", communeId: 26),
  SousPrefectureData(id: 227, nom: "Dougountouny", communeId: 26),
  SousPrefectureData(id: 228, nom: "Fougou", communeId: 26),
  SousPrefectureData(id: 229, nom: "Gayah", communeId: 26),
  SousPrefectureData(id: 230, nom: "Hidayatou", communeId: 26),
  SousPrefectureData(id: 231, nom: "Lebekere", communeId: 26),
  SousPrefectureData(id: 232, nom: "Madina Wora", communeId: 26),
  SousPrefectureData(id: 233, nom: "Mali centre", communeId: 26),
  SousPrefectureData(id: 234, nom: "Salambande", communeId: 26),
  SousPrefectureData(id: 235, nom: "Telire", communeId: 26),
  SousPrefectureData(id: 236, nom: "Touba", communeId: 26),
  SousPrefectureData(id: 237, nom: "Yembereng", communeId: 26),
  SousPrefectureData(id: 238, nom: "Fatako", communeId: 33),
  SousPrefectureData(id: 239, nom: "Fello Koundoua", communeId: 33),
  SousPrefectureData(id: 240, nom: "Kansangui", communeId: 33),
  SousPrefectureData(id: 241, nom: "Kolangui", communeId: 33),
  SousPrefectureData(id: 242, nom: "Kollet", communeId: 33),
  SousPrefectureData(id: 243, nom: "Konah", communeId: 33),
  SousPrefectureData(id: 244, nom: "Kouratongo", communeId: 33),
  SousPrefectureData(id: 245, nom: "Koyin", communeId: 33),
  SousPrefectureData(id: 246, nom: "Tangaly", communeId: 33),
  SousPrefectureData(id: 247, nom: "Tougue centre", communeId: 33),
  SousPrefectureData(id: 248, nom: "Bodie", communeId: 7),
  SousPrefectureData(id: 249, nom: "Dalaba centre", communeId: 7),
  SousPrefectureData(id: 250, nom: "Ditinn", communeId: 7),
  SousPrefectureData(id: 251, nom: "Kaalan", communeId: 7),
  SousPrefectureData(id: 252, nom: "Kankalabe", communeId: 7),
  SousPrefectureData(id: 253, nom: "Kebali", communeId: 7),
  SousPrefectureData(id: 254, nom: "Koba", communeId: 7),
  SousPrefectureData(id: 255, nom: "Mafara", communeId: 7),
  SousPrefectureData(id: 256, nom: "Mitty", communeId: 7),
  SousPrefectureData(id: 257, nom: "Mombeyah", communeId: 7),
  SousPrefectureData(id: 258, nom: "Bouliwel", communeId: 27),
  SousPrefectureData(id: 259, nom: "Dounet", communeId: 27),
  SousPrefectureData(id: 260, nom: "Gongoret", communeId: 27),
  SousPrefectureData(id: 261, nom: "Kegneko", communeId: 27),
  SousPrefectureData(id: 262, nom: "Konkoure", communeId: 27),
  SousPrefectureData(id: 263, nom: "Mamou centre", communeId: 27),
  SousPrefectureData(id: 264, nom: "Nyagara", communeId: 27),
  SousPrefectureData(id: 265, nom: "Oure Kaba", communeId: 27),
  SousPrefectureData(id: 266, nom: "Poredaka", communeId: 27),
  SousPrefectureData(id: 267, nom: "Saramoussaya", communeId: 27),
  SousPrefectureData(id: 268, nom: "Soyah", communeId: 27),
  SousPrefectureData(id: 269, nom: "Teguereya", communeId: 27),
  SousPrefectureData(id: 270, nom: "Timbo", communeId: 27),
  SousPrefectureData(id: 271, nom: "Tolo", communeId: 27),
  SousPrefectureData(id: 272, nom: "Bantignel", communeId: 30),
  SousPrefectureData(id: 273, nom: "Bourouwal Tappe", communeId: 30),
  SousPrefectureData(id: 274, nom: "Dongol Touma", communeId: 30),
  SousPrefectureData(id: 275, nom: "Gongore", communeId: 30),
  SousPrefectureData(id: 276, nom: "Ley-Miro", communeId: 30),
  SousPrefectureData(id: 277, nom: "Maci", communeId: 30),
  SousPrefectureData(id: 278, nom: "Ninguelande", communeId: 30),
  SousPrefectureData(id: 279, nom: "Pita centre", communeId: 30),
  SousPrefectureData(id: 280, nom: "Sangareah", communeId: 30),
  SousPrefectureData(id: 281, nom: "Sintaly", communeId: 30),
  SousPrefectureData(id: 282, nom: "Timbi-Madina", communeId: 30),
  SousPrefectureData(id: 283, nom: "Timbi-Touny", communeId: 30),
  SousPrefectureData(id: 284, nom: "Beyla centre", communeId: 1),
  SousPrefectureData(id: 285, nom: "Boola", communeId: 1),
  SousPrefectureData(id: 286, nom: "Diarraguerela", communeId: 1),
  SousPrefectureData(id: 287, nom: "Diassadou", communeId: 1),
  SousPrefectureData(id: 288, nom: "Fouala", communeId: 1),
  SousPrefectureData(id: 289, nom: "Gbackedou", communeId: 1),
  SousPrefectureData(id: 290, nom: "Gbessoba", communeId: 1),
  SousPrefectureData(id: 291, nom: "karala", communeId: 1),
  SousPrefectureData(id: 292, nom: "Koumandou", communeId: 1),
  SousPrefectureData(id: 293, nom: "Mousadou", communeId: 1),
  SousPrefectureData(id: 294, nom: "Nionsomoridou", communeId: 1),
  SousPrefectureData(id: 295, nom: "Samana", communeId: 1),
  SousPrefectureData(id: 296, nom: "Sinko", communeId: 1),
  SousPrefectureData(id: 297, nom: "Sokourala", communeId: 1),
  SousPrefectureData(id: 298, nom: "Bolodou", communeId: 14),
  SousPrefectureData(id: 299, nom: "Fangamadou", communeId: 14),
  SousPrefectureData(id: 300, nom: "Gueckedou centre", communeId: 14),
  SousPrefectureData(id: 301, nom: "Guendembou", communeId: 14),
  SousPrefectureData(id: 302, nom: "Kassadou", communeId: 14),
  SousPrefectureData(id: 303, nom: "Koundou", communeId: 14),
  SousPrefectureData(id: 304, nom: "Nongoa", communeId: 14),
  SousPrefectureData(id: 305, nom: "Ouende Kenema", communeId: 14),
  SousPrefectureData(id: 306, nom: "Tekoulo", communeId: 14),
  SousPrefectureData(id: 307, nom: "Termessadou Djibo", communeId: 14),
  SousPrefectureData(id: 308, nom: "Bossou", communeId: 24),
  SousPrefectureData(id: 309, nom: "Foumbadou", communeId: 24),
  SousPrefectureData(id: 310, nom: "Gama Berema", communeId: 24),
  SousPrefectureData(id: 311, nom: "Gueassou", communeId: 24),
  SousPrefectureData(id: 312, nom: "Kokota", communeId: 24),
  SousPrefectureData(id: 313, nom: "Laine", communeId: 24),
  SousPrefectureData(id: 314, nom: "Lola centre", communeId: 24),
  SousPrefectureData(id: 315, nom: "N'Zoo", communeId: 24),
  SousPrefectureData(id: 316, nom: "Tounkarata", communeId: 24),
  SousPrefectureData(id: 317, nom: "Balizia", communeId: 25),
  SousPrefectureData(id: 318, nom: "Binikala", communeId: 25),
  SousPrefectureData(id: 319, nom: "Bofossou", communeId: 25),
  SousPrefectureData(id: 320, nom: "Daro", communeId: 25),
  SousPrefectureData(id: 321, nom: "Fassankoni", communeId: 25),
  SousPrefectureData(id: 322, nom: "kouankan", communeId: 25),
  SousPrefectureData(id: 323, nom: "Koyama", communeId: 25),
  SousPrefectureData(id: 324, nom: "Macenta centre", communeId: 25),
  SousPrefectureData(id: 325, nom: "N'Zebela", communeId: 25),
  SousPrefectureData(id: 326, nom: "Oremai", communeId: 25),
  SousPrefectureData(id: 327, nom: "Panziazou", communeId: 25),
  SousPrefectureData(id: 328, nom: "Semgbedou", communeId: 25),
  SousPrefectureData(id: 329, nom: "Seredou", communeId: 25),
  SousPrefectureData(id: 330, nom: "Vaseredou", communeId: 25),
  SousPrefectureData(id: 331, nom: "Watanka", communeId: 25),
  SousPrefectureData(id: 332, nom: "Bounouma", communeId: 29),
  SousPrefectureData(id: 333, nom: "Gouecke", communeId: 29),
  SousPrefectureData(id: 334, nom: "Kobela", communeId: 29),
  SousPrefectureData(id: 335, nom: "Koropara", communeId: 29),
  SousPrefectureData(id: 336, nom: "Koule", communeId: 29),
  SousPrefectureData(id: 337, nom: "N'Zerekore centre", communeId: 29),
  SousPrefectureData(id: 338, nom: "Pale", communeId: 29),
  SousPrefectureData(id: 339, nom: "Samoe", communeId: 29),
  SousPrefectureData(id: 340, nom: "Soulouma", communeId: 29),
  SousPrefectureData(id: 341, nom: "Womey", communeId: 29),
  SousPrefectureData(id: 342, nom: "Yalenzou", communeId: 29),
  SousPrefectureData(id: 343, nom: "Banie", communeId: 34),
  SousPrefectureData(id: 344, nom: "Bheta", communeId: 34),
  SousPrefectureData(id: 345, nom: "Bignamou", communeId: 34),
  SousPrefectureData(id: 346, nom: "Bowe", communeId: 34),
  SousPrefectureData(id: 347, nom: "Diecke", communeId: 34),
  SousPrefectureData(id: 348, nom: "Pela", communeId: 34),
  SousPrefectureData(id: 349, nom: "Yomou centre", communeId: 34),
];

RegionData? findRegion(int id) {
  for (final r in regionsData) {
    if (r.id == id) return r;
  }
  return null;
}

CommuneData? findCommune(int id) {
  for (final c in communesData) {
    if (c.id == id) return c;
  }
  return null;
}

SousPrefectureData? findSousPrefecture(int id) {
  for (final s in sousPrefecturesData) {
    if (s.id == id) return s;
  }
  return null;
}

List<CommuneData> communesForRegion(int regionId) =>
    communesData.where((c) => c.regionId == regionId).toList();

List<SousPrefectureData> sousPrefecturesForCommune(int communeId) =>
    sousPrefecturesData.where((s) => s.communeId == communeId).toList();

/// "NOM (Région)" label — used where a commune is shown without its
/// parent region already visible elsewhere on the same form.
String communeLabelWithRegion(CommuneData commune) {
  final region = findRegion(commune.regionId);
  return region == null ? commune.nom : '${commune.nom} (${region.nom})';
}

/// "NOM (Commune)" label — used where a sous-préfecture is shown
/// without its parent commune already visible elsewhere on the form.
String sousPrefectureLabelWithCommune(SousPrefectureData sp) {
  final commune = findCommune(sp.communeId);
  return commune == null ? sp.nom : '${sp.nom} (${commune.nom})';
}
